# Generated by Django 5.2.12 on 2026-03-24 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_product_cost_price_alter_product_min_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Umumiy summa')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Kirim sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('total', models.IntegerField(default=0, verbose_name='Jami')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Tovar')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.purchase', verbose_name='Kirim')),
            ],
            options={
                'verbose_name': 'Kirim qatori',
                'verbose_name_plural': 'Kirim qatorlari',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Mijoz ismi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('waiting', "To'lov kutilmoqda"), ('paid', "To'langan")], default='draft', max_length=20, verbose_name='Holat')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Umumiy summa')),
                ('total_cost', models.IntegerField(default=0, verbose_name='Tan narxi summasi')),
                ('profit', models.IntegerField(default=0, verbose_name='Foyda')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sotuv sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('cost_price_snapshot', models.IntegerField(default=0, verbose_name='Tan narxi (sotilgan payt)')),
                ('total', models.IntegerField(default=0, verbose_name='Jami')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Tovar')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Sotuv qatori',
                'verbose_name_plural': 'Sotuv qatorlari',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Sotuv'), ('purchase', 'Kirim')], max_length=20, verbose_name='Turi')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('price', models.IntegerField(default=0, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Tovar')),
            ],
            options={
                'verbose_name': 'Tovar harakati',
                'verbose_name_plural': 'Tovar harakatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
