# Generated by Django 5.2.12 on 2026-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='price',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cost_price',
            field=models.IntegerField(default=0, verbose_name='Tan narxi'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='sell_price',
            field=models.IntegerField(default=0, verbose_name='Sotish narxi'),
        ),
    ]
