# Generated by Django 5.2.12 on 2026-03-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_purchaseitem_price_purchaseitem_cost_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='cost_price_snapshot',
        ),
    ]
