# Generated by Django 5.2.12 on 2026-03-26 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_purchaseitem_cost_price_and_more'),
        ('inventory', '0004_remove_product_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BazarSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Mijoz ismi')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Mijoz telefoni')),
                ('payment_status', models.CharField(choices=[('paid', "To'langan"), ('debt', 'Qarz')], default='paid', max_length=20, verbose_name="To'lov holati")),
                ('total_amount', models.IntegerField(default=0, verbose_name='Umumiy summa')),
                ('sale_date', models.DateField(verbose_name='Sotuv sanasi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Bozor sotuvi',
                'verbose_name_plural': 'Bozor sotuvlari',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BazarSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('total', models.IntegerField(default=0, verbose_name='Jami')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Tovar')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.bazarsale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Bozor sotuv qatori',
                'verbose_name_plural': 'Bozor sotuv qatorlari',
            },
        ),
        migrations.CreateModel(
            name='BazarStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Bozordagi soni')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bazar', to='inventory.product', verbose_name='Tovar')),
            ],
            options={
                'verbose_name': 'Bozordagi tovar',
                'verbose_name_plural': 'Bozordagi tovarlar',
            },
        ),
    ]
