# Generated by Django 5.2.12 on 2026-03-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_message'),
        ('inventory', '0004_remove_product_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dokon nomi')),
            ],
            options={
                'verbose_name': 'Dokon',
                'verbose_name_plural': 'Dokonlar',
            },
        ),
        migrations.AlterField(
            model_name='bazarstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bazar', to='inventory.product', verbose_name='Tovar'),
        ),
        migrations.AddField(
            model_name='bazarsale',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='finance.shop', verbose_name='Dokon'),
        ),
        migrations.AddField(
            model_name='bazarstock',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='finance.shop', verbose_name='Dokon'),
        ),
        migrations.AlterUniqueTogether(
            name='bazarstock',
            unique_together={('product', 'shop')},
        ),
    ]
