# Generated by Django 5.2.12 on 2026-04-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_bazarsaleitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BozorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('payment_date', models.DateField(verbose_name='Sana')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Bozordan pul',
                'verbose_name_plural': 'Bozordan pullar',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
