# Generated by Django 5.2.12 on 2026-05-02 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_bozorpayment'),
        ('inventory', '0005_pricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date', '-created_at'], 'verbose_name': 'Sotuv', 'verbose_name_plural': 'bozorga ketuvlar'},
        ),
        migrations.CreateModel(
            name='BazarMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_before', models.IntegerField(verbose_name='Oldin')),
                ('quantity_after', models.IntegerField(verbose_name='Keyin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Tovar')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.shop', verbose_name='Dokon')),
            ],
            options={
                'verbose_name': 'Bozor harakati',
                'verbose_name_plural': 'Bozor harakatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
