# Generated by Django 5.2.12 on 2026-05-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_sale_options_bazarmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bozorpayment',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.shop', verbose_name='Dokon'),
        ),
    ]
