# Generated by Django 5.2.12 on 2026-05-05 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_bozorpayment_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bozorpayment',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.shop', verbose_name='Dokon'),
        ),
    ]
