# Generated by Django 5.2.12 on 2026-05-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_bozorpayment_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bozorpayment',
            name='category',
            field=models.CharField(blank=True, choices=[('xitoy', 'Xitoy'), ('seh', 'Seh')], max_length=10, null=True, verbose_name='Kategoriya'),
        ),
    ]
