# Generated by Django 5.2.12 on 2026-06-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_bozorpayment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazarsale',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name="To'lov sanasi"),
        ),
    ]
