[program:sklad]
command=/home/sklad/sklad/venv/bin/gunicorn config.wsgi:application --workers 2 --bind 127.0.0.1:8000
directory=/home/sklad/sklad
user=sklad
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/sklad.log
stderr_logfile=/var/log/supervisor/sklad_error.log
