# Generated by Django 5.2.12 on 2026-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.IntegerField(default=0, verbose_name='Tan narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='Minimal qoldiq'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.IntegerField(default=0, verbose_name='Sotish narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Qoldiq'),
        ),
    ]
