# Generated by Django 5.2.12 on 2026-03-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_cost_price_alter_product_min_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='per_box',
            field=models.IntegerField(default=1, verbose_name='1 korobkada'),
        ),
    ]
