# Generated by Django 5.2.12 on 2026-04-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.IntegerField(verbose_name='Eski narx')),
                ('new_price', models.IntegerField(verbose_name='Yangi narx')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgargan sana")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.product', verbose_name='Tovar')),
            ],
            options={
                'verbose_name': 'Narx tarixi',
                'verbose_name_plural': 'Narx tarixi',
                'ordering': ['-changed_at'],
            },
        ),
    ]
