# Generated by Django 5.2.12 on 2026-05-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='QogozRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('record_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], default='in', max_length=5, verbose_name='Turi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qogoz_records', to='inventory.product')),
            ],
            options={
                'verbose_name': "Qog'oz",
                'verbose_name_plural': "Qog'oz tarixi",
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
