# Generated by Django 5.2.12 on 2026-05-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_qogozrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qogoz_stock',
            field=models.IntegerField(default=0, verbose_name="Qog'oz qoldig'i"),
        ),
    ]
