# Generated by Django 5.2.12 on 2026-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_qogoz_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qogoz_per_unit',
            field=models.IntegerField(default=1, verbose_name="1 donaga qog'oz"),
        ),
    ]
